//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVVoyage.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VVVoyage.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start a route, simply click the route button on the main menu screen. You are then able to choose any route you&apos;d like. The route will start right away! Follow the line on the screen to arrive at the next landmark. You will get a notification once you&apos;re close. The app will give a useful name and description for the landmark as well. Admire its beauty, and then visit the next landmark. The tour will automatically end once you&apos;ve visited all landmarks of the route..
        /// </summary>
        internal static string App_Instructions {
            get {
                return ResourceManager.GetString("App_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Ensure that the GPS functionality on your phone is working and that this app has access to it;.
        /// </summary>
        internal static string Ensure_Gps {
            get {
                return ResourceManager.GetString("Ensure_Gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Make sure the app has access to location, even when the app is inactive. So not only while using the app, but also in the background..
        /// </summary>
        internal static string Ensure_Permissions {
            get {
                return ResourceManager.GetString("Ensure_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Ensure that you are using Wi-Fi or cellular data throughout the tour;.
        /// </summary>
        internal static string Ensure_Wifi {
            get {
                return ResourceManager.GetString("Ensure_Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General outline.
        /// </summary>
        internal static string General_Outline {
            get {
                return ResourceManager.GetString("General_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        internal static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmark.
        /// </summary>
        internal static string Landmark_Default_Label {
            get {
                return ResourceManager.GetString("Landmark_Default_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You visited the last landmark on {0} with id {1}. Note that this progress will not be updated on the map!.
        /// </summary>
        internal static string Landmark_Progress_Message {
            get {
                return ResourceManager.GetString("Landmark_Progress_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmark progress.
        /// </summary>
        internal static string Landmark_Progress_Title {
            get {
                return ResourceManager.GetString("Landmark_Progress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tour cannot be started, because the phone&apos;s location services (including GPS services) have been disabled. Hint: re-enable location services by going to the Quick Settings menu (swipe down from the top) and activate the tile named &apos;Location&apos;..
        /// </summary>
        internal static string Location_Disabled_Message {
            get {
                return ResourceManager.GetString("Location_Disabled_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: location disabled.
        /// </summary>
        internal static string Location_Disabled_Title {
            get {
                return ResourceManager.GetString("Location_Disabled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS location permission is required to use this app..
        /// </summary>
        internal static string Location_Permission_Message {
            get {
                return ResourceManager.GetString("Location_Permission_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission required.
        /// </summary>
        internal static string Location_Permission_Title {
            get {
                return ResourceManager.GetString("Location_Permission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head to:.
        /// </summary>
        internal static string Navigation_Instruction {
            get {
                return ResourceManager.GetString("Navigation_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next landmark.
        /// </summary>
        internal static string Next_Landmark {
            get {
                return ResourceManager.GetString("Next_Landmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next sight:.
        /// </summary>
        internal static string Next_Sight {
            get {
                return ResourceManager.GetString("Next_Sight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue tour.
        /// </summary>
        internal static string No_Internet_Continue {
            get {
                return ResourceManager.GetString("No_Internet_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, it looks like you don&apos;t have internet access! This may happen when you&apos;re switching Wi-Fi networks, or when switching from Wi-Fi to cellular data. Continuing the tour might help..
        /// </summary>
        internal static string No_Internet_Message {
            get {
                return ResourceManager.GetString("No_Internet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop tour.
        /// </summary>
        internal static string No_Internet_Stop {
            get {
                return ResourceManager.GetString("No_Internet_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet.
        /// </summary>
        internal static string No_Internet_Title {
            get {
                return ResourceManager.GetString("No_Internet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app cannot work on this phone, since it does not have a GPS..
        /// </summary>
        internal static string No_Location_Support_Message {
            get {
                return ResourceManager.GetString("No_Location_Support_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS not supported.
        /// </summary>
        internal static string No_Location_Support_Title {
            get {
                return ResourceManager.GetString("No_Location_Support_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tour cannot be started, because the phone is too far away from Breda! Hint: if you&apos;re running an emulator, set the emulator location to somewhere in Breda in the emulator settings..
        /// </summary>
        internal static string Phone_Too_Far_Away_Message {
            get {
                return ResourceManager.GetString("Phone_Too_Far_Away_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: too far away.
        /// </summary>
        internal static string Phone_Too_Far_Away_Title {
            get {
                return ResourceManager.GetString("Phone_Too_Far_Away_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t decide which tour to take? Let the app decide a tour for you..
        /// </summary>
        internal static string Random_Tour_Description {
            get {
                return ResourceManager.GetString("Random_Tour_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random tour.
        /// </summary>
        internal static string Random_Tour_Name {
            get {
                return ResourceManager.GetString("Random_Tour_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▼ Scroll this page to see more ▼.
        /// </summary>
        internal static string Scroll_Page_Instruction {
            get {
                return ResourceManager.GetString("Scroll_Page_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select_Instruction {
            get {
                return ResourceManager.GetString("Select_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tour.
        /// </summary>
        internal static string Select_Tour {
            get {
                return ResourceManager.GetString("Select_Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop the tour? Your progress will be lost!.
        /// </summary>
        internal static string Stop_Route_Confirmation {
            get {
                return ResourceManager.GetString("Stop_Route_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have finished the tour! We hope you had a wonderful experience!.
        /// </summary>
        internal static string Tour_End_Message {
            get {
                return ResourceManager.GetString("Tour_End_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour finished!.
        /// </summary>
        internal static string Tour_End_Title {
            get {
                return ResourceManager.GetString("Tour_End_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Closing the app while doing the tour, stops the tour..
        /// </summary>
        internal static string Warning_Close {
            get {
                return ResourceManager.GetString("Warning_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to VVVoyage, your tour guide through Breda!.
        /// </summary>
        internal static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
