//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVVoyage.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VVVoyage.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover some of the oldest landmarks of Breda. Find out what cultural significance they still have today..
        /// </summary>
        internal static string Antique_Description {
            get {
                return ResourceManager.GetString("Antique_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start a route, simply click the route button on the main menu screen. You are then able to choose any route you&apos;d like. The route will start right away! Follow the line on the screen to arrive at the next landmark. You will get a notification once you&apos;re close. The app will give a useful name and description for the landmark as well. Admire its beauty, and then visit the next landmark. The tour will automatically end once you&apos;ve visited all landmarks of the route..
        /// </summary>
        internal static string App_Instructions {
            get {
                return ResourceManager.GetString("App_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breda Castle was once the ancestral home of the Nassaus, the ancestors of our royal family. Because of the important international role of the Nassaus, the Castle was an important place in Europe during the 15th to 17th centuries.
        ///
        ///A long history
        ///Breda Castle has a long history. A castle stood on the site of the current castle as early as 1198. The castle came into the hand of the Nassaus in the early 15th century through the marriage of German count Engelbrecht van Nassau to Breda’s Johanna van Polanen. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Castle_Description {
            get {
                return ResourceManager.GetString("Castle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Ensure that the GPS functionality on your phone is working and that this app has access to it;.
        /// </summary>
        internal static string Ensure_Gps {
            get {
                return ResourceManager.GetString("Ensure_Gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Ensure that you are using Wi-Fi or cellular data throughout the tour;.
        /// </summary>
        internal static string Ensure_Wifi {
            get {
                return ResourceManager.GetString("Ensure_Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breda is home to some of the most unique snacks and meals. Ever wanted to know what a frikandel or a kroket tastes like?.
        /// </summary>
        internal static string Food_Description {
            get {
                return ResourceManager.GetString("Food_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General outline.
        /// </summary>
        internal static string General_Outline {
            get {
                return ResourceManager.GetString("General_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        internal static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officially, this statue is called the &quot;Liefdeszuster of St. Vincent de St. Paul de Chartres.&quot; It symbolizes the religious history of Breda. The creator, Jos van Riemsdijk, depicts with the Liefdeszuster the care that the hospice sisters practiced for centuries.
        ///
        ///The Meeùs concern donated the statue in 1990..
        /// </summary>
        internal static string Liefdeszusters_Description {
            get {
                return ResourceManager.GetString("Liefdeszusters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certainly noteworthy, a lighthouse in the Breda canal. It is not intended to guide seafaring vessels, though. &quot;The Lighthouse&quot; is an artwork by the Italian architect/artist Aldo Rossi. The idea for a Rossi artwork in Breda originated when he exhibited in the Breda Beyerd in the 1980s (the current location of the Stedelijk Museum). Rossi had previously exhibited lighthouses in Toronto and Rotterdam, and in 1992, &quot;The Lighthouse&quot; was installed in Breda. Initially placed in the Wilhelminavijver, it found its p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Light_House_Description {
            get {
                return ResourceManager.GetString("Light_House_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Nassau Monument, also known as the Baroniemonument, commemorates the arrival of the German Count Engelbrecht of Nassau in the Netherlands. The three reliefs depict the inauguration of Engelbrecht and his wife, the eleven-year-old Johanna van Polanen from Breda, as Lord and Lady of Breda. Through their marriage, Engelbrecht and Johanna laid the foundation for the House of Orange-Nassau, our Dutch Royal Family.
        ///
        ///The monument was ceremoniously unveiled in 1905 by Queen Wilhelmina. Around it, the coats of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nassau_Description {
            get {
                return ResourceManager.GetString("Nassau_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head to:.
        /// </summary>
        internal static string Navigation_Instruction {
            get {
                return ResourceManager.GetString("Navigation_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next sight:.
        /// </summary>
        internal static string Next_Sight {
            get {
                return ResourceManager.GetString("Next_Sight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the beginning of the COVID-19 crisis, the Breda Tourist Information Office (VVV) had to close its doors. A few months later, in June, it was decided that this closure would be permanent. The store had been experiencing losses for quite some time, and efforts to turn the tide proved unsuccessful. In July of that year, CoffeeLab took over the space on Willemstraat. Since then, it has been a place to enjoy a cup of coffee, lunch, or work at one of the flexible workspaces.
        ///
        ///However, a bit of the VVV is mak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Old_VVV_Description {
            get {
                return ResourceManager.GetString("Old_VVV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t decide which tour to take? Let the app decide a tour for you..
        /// </summary>
        internal static string Random_Tour_Description {
            get {
                return ResourceManager.GetString("Random_Tour_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random tour.
        /// </summary>
        internal static string Random_Tour_Name {
            get {
                return ResourceManager.GetString("Random_Tour_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tour.
        /// </summary>
        internal static string Select_Tour {
            get {
                return ResourceManager.GetString("Select_Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop the tour? Your progress will be lost!.
        /// </summary>
        internal static string Stop_Route_Confirmation {
            get {
                return ResourceManager.GetString("Stop_Route_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-way ticket to Wagenberg (if it even exists). You&apos;ll probably die alone on this tour..
        /// </summary>
        internal static string Wagenberg_Description {
            get {
                return ResourceManager.GetString("Wagenberg_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Closing the app while doing the tour stops the tour..
        /// </summary>
        internal static string Warning_Close {
            get {
                return ResourceManager.GetString("Warning_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to VVVoyage, your tour guide through Breda!.
        /// </summary>
        internal static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
